<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\DownloadGedcomWithURL;

use Fisharebest\Webtrees\Encodings\ANSEL;
use Fisharebest\Webtrees\Encodings\ASCII;
use Fisharebest\Webtrees\Encodings\UTF16BE;
use Fisharebest\Webtrees\Encodings\UTF8;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;


/**
 * @var  string                 $title,
 * @var  Tree                   $tree,
 * @var  string                 $data_folder,
 * @var  bool                   $zip_available
 * @var  string                 $control_panel_secret_key
 * @var  string                 $default_action
 * @var  string                 $default_format
 * @var  string                 $default_encoding
 * @var  string                 $default_endings
 * @var  string                 $default_privacy
 * @var  string                 $default_time_stamp
 * @var  array                  $gedcom_filter_list
 * @var  string                 $default_gedcom_filter1
 * @var  string                 $default_gedcom_filter2
 * @var  string                 $default_gedcom_filter3
 */

//ToDo: e($variable) 
?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(SettingsPage::class) => I18N::translate('Extended Import/Export'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post" action="<?= e(route(DownloadGedcomWithURL::class, [
			'key'       => $control_panel_secret_key . Session::getCsrfToken(),
		])) ?>" class="form form-horizontal">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Select a tree') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', ['name' => 'tree', 'selected' => $tree->name(), 
				'options' => $tree_list]) ?>
		</div>
	</div>	

	<div class="row mb-3">
		<label class="col-sm-3" for="format">
			<?= I18N::translate('Format') ?>
		</label>

		<div class="col-sm-9">
			<div class="form-check">
				<input class="form-check-input" type="radio" name="format" id="format-gedcom" value="gedcom" <?= $default_format === 'gedcom' ? 'checked="checked"' : '' ?> data-wt-extension=".ged">

				<label class="form-check-label" for="format-gedcom">
					<?= I18N::translate('GEDCOM') ?>
				</label>
			</div>

			<div class="form-check">
				<input class="form-check-input" type="radio" name="format" id="format-zip" value="zip" <?= $default_format === 'zip' ? 'checked="checked"' : '' ?> data-wt-extension=".zip" <?= $zip_available ? '' : 'disabled="disabled"'?>>

				<label class="form-check-label" for="format-zip">
					<?= /* I18N: ZIP = file format */ I18N::translate('ZIP') ?>
				</label>
			</div>

			<div class="form-check">
				<input class="form-check-input" type="radio" name="format" id="format-zipmedia" value="zipmedia" <?= $default_format === 'zipmedia' ? 'checked="checked"' : '' ?> data-wt-extension=".zip" <?= $zip_available ? '' : 'disabled="disabled"'?>>

				<label class="form-check-label" for="format-zipmedia">
					<?= /* I18N: ZIP = file format */ I18N::translate('ZIP') ?>
					<?= I18N::translate('(includes media files)') ?>
				</label>
			</div>

			<div class="form-check">
				<input class="form-check-input" type="radio" name="format" id="format-gdz" value="gedzip" <?= $default_format === 'gedzip' ? 'checked="checked"' : '' ?> data-wt-extension=".gdz" <?= $zip_available ? '' : 'disabled="disabled"'?>>

				<label class="form-check-label" for="format-gdz">
					<?= /* I18N: GEDZIP = file format */ I18N::translate('GEDZIP') ?>
					<?= I18N::translate('(includes media files)') ?>
				</label>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-sm-3" for="filename">
			<?= I18N::translate('Filename') ?>
		</label>

		<div class="col-sm-9">
			<div class="input-group">
				<input class="form-control" id="filename" name="filename" type="text" value="">
				<span class="input-group-text" id="extension">.ged</span>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-sm-3" for="encoding">
			<?= I18N::translate('Character encoding') ?>
		</label>

		<div class="col-sm-9">
			<?= view('components/select', ['name' => 'encoding', 'id' => 'encoding', 'selected' => $default_encoding, 'options' => [UTF8::NAME => 'UTF-8', UTF16BE::NAME => 'UNICODE (UTF16-BE)', ANSEL::NAME => 'ANSEL', ASCII::NAME => 'ASCII', 'CP1252' => 'ANSI (CP1252)']]) ?>
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-sm-3" for="line_endings">
			<?= I18N::translate('Line endings') ?>
		</label>

		<div class="col-sm-9">
			<?= view('components/radios-inline', ['name' => 'line_endings', 'options' => ['CRLF' => 'CR/LF (windows)', 'LF' => 'LF (unix)'], 'selected' => $default_endings]) ?>
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-sm-3" for="privacy">
			<?= I18N::translate('Apply privacy settings') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/radios-inline', ['name' => 'privacy','selected' => e($default_privacy), 
				'options' => [
					'none'     => 'none (' . I18N::translate('None') .')', 
					'gedadmin' => 'gedadmin (' . I18N::translate('Manager') .')', 
					'user'     => 'user (' . I18N::translate('Member') .')',  
					'visitor'  => 'visitor (' . I18N::translate('Visitor') .')', 
				]
			]) ?>
		</div>
	</div>

	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Time stamp') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => 'time_stamp', 'selected' => $default_time_stamp,
					'options' => [
						DownloadGedcomWithURL::TIME_STAMP_NONE    => DownloadGedcomWithURL::TIME_STAMP_NONE    . ' (' . I18N::translate('No time stamp') . ')',
						DownloadGedcomWithURL::TIME_STAMP_PREFIX  => DownloadGedcomWithURL::TIME_STAMP_PREFIX  . ' (' .  I18N::translate('Prefix time stamp') . ')',
						DownloadGedcomWithURL::TIME_STAMP_POSTFIX => DownloadGedcomWithURL::TIME_STAMP_POSTFIX . ' (' . I18N::translate('Postfix time stamp') . ')',
					] 
				]) ?>
			</div>
		</div>
	</fieldset>		

	<div class="h4">
		<?= I18N::translate('Export action') ?>
	</div>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Action') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => 'action', 'selected' => $default_action,
					'options' => [
						DownloadGedcomWithURL::ACTION_DOWNLOAD => I18N::translate('Download'),
						DownloadGedcomWithURL::ACTION_SAVE     => I18N::translate('Save on the webtrees server'),
						DownloadGedcomWithURL::ACTION_BOTH     => I18N::translate('Both, i.e. download and save in parallel'),
					]
				]) ?>
			</div>
		</div>
	</fieldset>		

	<div class="h4">
		<?= I18N::translate('Select GEDCOM filters') ?>
	</div>
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Gedcom filter %s', '1') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', ['name' => 'gedcom_filter1', 'selected' => $default_gedcom_filter1, 
				'options' => $gedcom_filter_list]) ?>
		</div>
	</div>		
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Gedcom filter %s', '2') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', ['name' => 'gedcom_filter2', 'selected' => $default_gedcom_filter2, 
				'options' => $gedcom_filter_list]) ?>
		</div>
	</div>		
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Gedcom filter %s', '3') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', ['name' => 'gedcom_filter3', 'selected' => $default_gedcom_filter3, 
				'options' => $gedcom_filter_list]) ?>
		</div>
	</div>

	<div class="row mb-3">
		<div class="col">
			<button type="submit" class="btn btn-primary">
				<?= view('icons/download') ?>
				<?= /* I18N: A button label. */
				I18N::translate('Export GEDCOM file') ?>
			</button>
		</div>
	</div>		

</form>

<?php View::push('javascript') ?>
<script>
	'use strict';

	document.querySelectorAll('[name=format]').forEach(element => element.addEventListener('change', event => document.getElementById('extension').innerText = event.target.dataset.wtExtension));

	// Firefox will reload the page and change the selected item.
	document.getElementById('extension').innerText = document.querySelector('[name=format]:checked').dataset.wtExtension;

</script>
<?php View::endpush(); ?>
