<?php

namespace Jefferson49\Webtrees\Module\DownloadGedcomWithURL;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;


/**
 * @var  string                 $title,
 * @var  Tree                   $tree,
 * @var  string                 $folder,
 * @var  Collection<int,string> $gedcom_files,
 * @var  string                 $control_panel_secret_key
 * @var  array                  $gedcom_filter_list
 * @var  string                 $default_gedcom_filter1
 * @var  string                 $default_gedcom_filter2
 * @var  string                 $default_gedcom_filter3
 */

 $default_gedcom_file = $tree->getPreference('gedcom_filename');
 $gedcom_media_path   = $tree->getPreference('GEDCOM_MEDIA_PATH');

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(SettingsPage::class) => I18N::translate('Extended Import/Export'), e($title)]]) ?>

<h1><?=e($title) ?></h1>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="alert alert-warning">
    <?= /* I18N: %s is the name of a family tree */ I18N::translate('Any import will delete all the genealogy data of the tree in the database and replace it with data from a GEDCOM file.') ?>
</div>

<form method="post" action="<?= e(route(DownloadGedcomWithURL::class, [
		'key'       => $control_panel_secret_key . Session::getCsrfToken(),
		'action'	=> DownloadGedcomWithURL::ACTION_UPLOAD,
		])) ?>" enctype="multipart/form-data">

	<?= csrf_field() ?>
	<input type="hidden" id="tree" value="<?= $tree->name() ?>">
	<input type="hidden" id="gedcom_filename" value="<?= e($default_gedcom_file) ?>">
	
		<div class="h4">
			<?= I18N::translate('Select a GEDCOM file to import') ?>
		</div>
		<div class="row mb-3">
			<label class="col-form-label col-sm-3">
				<input type="radio" name="source" id="import-client" value="client" checked>
				<?= I18N::translate('A file on your computer') ?>
			</label>
			<div class="col-sm-8">
				<input id="import-client-file" type="file" name="client_file" class="form-control">
			</div>
		</div>
		<div class="row mb-3">
			<label class="col-form-label col-sm-3">
				<input type="radio" name="source" id="import-server" value="server">
				<?= I18N::translate('A file on the server') ?>
			</label>
			<div class="col-sm-8">
				<div class="input-group" dir="ltr">
					<span class="input-group-text" dir="ltr">
						<?= e($folder) ?>
					</span>

					<select name="server_file" class="form-select" dir="ltr" id="import-server-file">
						<option selected="selected" value="">&nbsp;</option>
						<?php foreach ($gedcom_files as $gedcom_file) : ?>
							<option value="<?= e($gedcom_file) ?>" <?= $gedcom_file === $default_gedcom_file ? 'selected' : '' ?>>
								<?= e($gedcom_file) ?>
							</option>
						<?php endforeach ?>
						<?php if ($gedcom_files->isEmpty()) : ?>
							<option disabled selected>
								<?= I18N::translate('No GEDCOM files found.') ?>
							</option>
						<?php endif ?>
					</select>
				</div>
			</div>
		</div>	
		
		<div class="h4">
			<?= I18N::translate('Settings for GEDCOM Import') ?>
		</div>
		<div class="row mb-3">
			<label for="import_encoding" class="col-sm-3">
				<?= I18N::translate('Character encoding') ?>
			</label>
			<div class="col-sm-9">
				<?= view('components/select', ['name' => 'import_encoding', 'selected' => '', 'options' => ['' => I18N::translate('automatic')] + Registry::encodingFactory()->list()]) ?>
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-sm-3">
				<?= /* I18N: A configuration setting */ I18N::translate('Keep media objects') ?>
			</div>
			<div class="col-sm-9">
				<div class="form-check">
					<input type="checkbox" class="form-check-input" name="keep_media" id="keep_media" value="1" <?= $tree->getPreference('keep_media') ? 'checked' : '' ?>>
					<label for="keep_media" class="form-check-label">
						<?= I18N::translate('If you have created media objects in webtrees, and have subsequently edited this GEDCOM file using genealogy software that deletes media objects, then select this option to merge the current media objects with the new GEDCOM file.') ?>
					</label>
				</div>
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-sm-3">
				<?= I18N::translate('Add spaces where long lines were wrapped') ?>
			</div>
			<div class="col-sm-9">
				<div class="form-check">
					<input type="checkbox" class="form-check-input" name="WORD_WRAPPED_NOTES" id="WORD_WRAPPED_NOTES" value="1" <?= $tree->getPreference('WORD_WRAPPED_NOTES') ? 'checked' : '' ?>>
					<label for="WORD_WRAPPED_NOTES" class="form-check-label">
						<?= I18N::translate('If you created this GEDCOM file using genealogy software that omits spaces when splitting long lines, then select this option to reinsert the missing spaces.') ?>
					</label>
				</div>
			</div>
		</div>
		<div class="row mb-3">
			<label for="GEDCOM_MEDIA_PATH" class="col-sm-3">
				<?= /* I18N: A media path (e.g. c:\aaa\bbb\ccc\ddd.jpeg) in a GEDCOM file */ I18N::translate('Remove the GEDCOM media path from filenames') ?>
			</label>

			<div class="col-sm-9">
				<input class="form-control" dir="ltr" id="GEDCOM_MEDIA_PATH" maxlength="255" name="GEDCOM_MEDIA_PATH" type="text" value="<?= e($gedcom_media_path) ?>">
				<div class="form-text">
					<?= /* I18N: Help text for the “GEDCOM media path” configuration setting. A “path” is something like “C:\Documents\Genealogy\Photos\John_Smith.jpeg” */ I18N::translate('Some genealogy software creates GEDCOM files that contain media filenames with full paths. These paths will not exist on the web-server. To allow webtrees to find the file, the first part of the path must be removed.') ?>
					<?= /* I18N: Help text for the “GEDCOM media path” configuration setting. %s are all folder names */ I18N::translate('For example, if the GEDCOM file contains %1$s and webtrees expects to find %2$s in the media folder, then you would need to remove %3$s.', '<code>C:\\Documents\\family\\photo.jpeg</code>', '<code>family/photo.jpeg</code>', '<code>C:\\Documents\\</code>') ?>
				</div>
			</div>
		</div>

		<div class="h4">
			<?= I18N::translate('Select GEDCOM filters') ?>
		</div>
		<div class="row mb-3">
			<label class="col-form-label col-sm-3">
				<?= I18N::translate('Gedcom filter %s', '1') ?>
			</label>
			<div class="col-sm-3">
				<?= view('components/select', [
					'name'     => 'gedcom_filter1',
					'selected' => $default_gedcom_filter1, 
					'options'  => $gedcom_filter_list,
					]) ?>
			</div>
		</div>		
		<div class="row mb-3">
			<label class="col-form-label col-sm-3">
				<?= I18N::translate('Gedcom filter %s', '2') ?>
			</label>
			<div class="col-sm-3">
				<?= view('components/select', [
					'name'     => 'gedcom_filter2',
					'selected' => $default_gedcom_filter2, 
					'options'  => $gedcom_filter_list,
					]) ?>
			</div>
		</div>		
		<div class="row mb-3">
			<label class="col-form-label col-sm-3">
				<?= I18N::translate('Gedcom filter %s', '3') ?>
			</label>
			<div class="col-sm-3">
				<?= view('components/select', [
					'name'     => 'gedcom_filter3',
					'selected' => $default_gedcom_filter3, 
					'options'  => $gedcom_filter_list,
					]) ?>
			</div>
		</div>		

		<div class="row mb-3">
			<div class="col">
				<button type="submit" class="btn btn-primary" data-wt-confirm="<?= I18N::translate('Are you absolutely sure you want to import the selected file into the specified tree? Please be aware that importing the file will delete all existing data in the tree without possibility to recover! Therefore, also consider to backup the webtrees database before importing new files.') ?>">
					<?= view('icons/upload') ?>
					<?= I18N::translate('Import GEDCOM file') ?>
				</button>
			</div>
		</div>
	</input>		
</form>

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
	function checkGedcomImportForm (message) {
		let oldFile = $('#filename').val();
		let method = $('input[name=source]:checked').val();
		let newFile = method === 'server' ? $('#import-server-file').val() : $('#import-client-file').val();

		// Some browsers include c:\fakepath\ in the filename.
		newFile = newFile.replace(/.*[/\\]/, '');
		if (newFile !== oldFile && oldFile !== '') {
		return window.confirm(message);
		} else {
		return true;
		}
	};
</script>
<?php View::endpush() ?>