<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\ExtendedImportExport;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Helpers\ClassName;
use Jefferson49\Webtrees\Helpers\Functions;
use Jefferson49\Webtrees\Internationalization\MoreI18N;

use function e;

/**
 * @var  string	  $title
 * @var  Tree     $tree
 * @var  array    $tree_list
 * @var  string   $default_gedcom_filter1
 * @var  string   $default_gedcom_filter2
 * @var  string   $default_gedcom_filter3
 */

$module_service           = New ModuleService();

/** @var DownloadGedcomWithURL $download_gedcom_with_url */
$download_gedcom_with_url = Functions::getFromContainer(DownloadGedcomWithURL::class);

?>

<h1><?=e($title) ?></h1>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form" action="<?= e(route(SelectionPage::class)) ?>">
	<div class="row mb-3">
		<label class="col-form-label col-sm-3" for="tree">
			<?= I18N::translate('Select a tree') ?>
		</label>
		<div class="col-sm-9" id="tree-select">
			<?= view('components/select', ['name' => 'tree_name', 'selected' => $tree->name(),
				'options' => $tree_list]) ?>
		</div>
	</div>

	<ul class="fa-ul mx-0">
		<li>
			<span class="fa-li"><?= view('icons/upload') ?></span>
			<a href="<?= e(route(ImportGedcomPage::class, [
				'tree_name'      => $tree->name(),
				'gedcom_filter1' => $default_gedcom_filter1,
				'gedcom_filter2' => $default_gedcom_filter2,
				'gedcom_filter3' => $default_gedcom_filter3,
				])) ?>">
				<?= I18N::translate('GEDCOM Import') ?>
			</a>
		</li>
		<li>
			<span class="fa-li"><?= view('icons/download') ?></span>
			<a href="<?= e(route(ExportGedcomPage::class, [
				'tree_name'              => $tree->name(),
				'export_clippings_cart'  => false,
				'gedcom_filter1'         => $default_gedcom_filter1,
				'gedcom_filter2'         => $default_gedcom_filter2,
				'gedcom_filter3'         => $default_gedcom_filter3,
				'GEDBAS_Id'              => $tree->getPreference(DownloadGedcomWithURL::TREE_PREF_GEDBAS_ID, ''),
				'GEDBAS_title'           => '',
				'GEDBAS_description'     => '',
				])) ?>">
				<?= I18N::translate('GEDCOM Export: Tree') ?>
			</a>
		</li>
		<li>
			<span class="fa-li"><?= view('icons/download') ?></span>
			<a href="<?= e(route(ExportGedcomPage::class, [
				'tree_name'              => $tree->name(),
				'export_clippings_cart'  => true,
				'gedcom_filter1'         => $default_gedcom_filter1,
				'gedcom_filter2'         => $default_gedcom_filter2,
				'gedcom_filter3'         => $default_gedcom_filter3,
				'GEDBAS_Id'              => '',
				'GEDBAS_title'           => '',
				'GEDBAS_description'     => '',
				])) ?>">
				<?= I18N::translate('GEDCOM Export: Clippings cart') ?>
			</a>
		</li>
		<li>
			<span class="fa-li"><?= view('icons/copy') ?></span>
			<a href="<?= e(route(ConvertGedcomPage::class, [
				'gedcom_filter1'         => $default_gedcom_filter1,
				'gedcom_filter2'         => $default_gedcom_filter2,
				'gedcom_filter3'         => $default_gedcom_filter3,
				])) ?>">
				<?= I18N::translate('GEDCOM Conversion') ?>
			</a>
		</li>
		<li>
			<span class="fa-li"><?= view('icons/data-fix') ?></span>
			<a href="<?= e(route(ClassName::get(ClassName::DATA_FIX_PAGE), [
					'tree'     => $tree->name(),
					'data_fix' => $download_gedcom_with_url->name(),
					])) ?>">
				<?= I18N::translate('Datafix using GEDCOM filters') ?>
			</a>
		</li>
		<li>
			<div class="row mb-3"><?= view('icons/spacer') ?></div>
		</li>
		<li>
			<span class="fa-li"><?= view('icons/preferences') ?></span>
			<a href="<?= e($download_gedcom_with_url->getConfigLink()) ?>" title="<?= MoreI18N::xlate('Preferences') ?>">
				<?= MoreI18N::xlate('Preferences') ?>
			</a>
		</li>
	</ul>
	<?= csrf_field() ?>
</form>

<?php View::push('javascript') ?>
<script>
	document.querySelector('#tree-select select').addEventListener('change', function () {
        document.getElementById('settings-form').submit();
    });
</script>
<?php View::endpush() ?>