<?php

namespace Jefferson49\Webtrees\Module\ExtendedImportExport;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Encodings\ANSEL;
use Fisharebest\Webtrees\Encodings\ASCII;
use Fisharebest\Webtrees\Encodings\UTF16BE;
use Fisharebest\Webtrees\Encodings\UTF8;
use Fisharebest\Webtrees\Encodings\Windows1252;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Site;
use Fisharebest\Webtrees\View;

use function e;

/**
 * @var  string		$title
 * @var  bool		$use_hash
 * @var  string		$secret_key
 * @var  bool       $show_menu_list_item
 * @var  bool       $allow_remote_download
 * @var  bool       $allow_remote_upload
 * @var  bool       $allow_remote_save
 * @var  bool       $allow_remote_convert
 * @var  string		$folder_to_save 
 * @var  array      $gedcom_filter_list
 * @var  string     $default_gedcom_filter1
 * @var  string     $default_gedcom_filter2
 * @var  string     $default_gedcom_filter3
 * @var  string     $default_privacy_level 
 * @var  string     $default_export_format
 * @var  string     $default_encoding
 * @var  string     $default_ending
 * @var  string     $default_time_stamp
 * @var  bool       $default_gedcom_version
 * @var  bool       $default_gedcom_l_selection
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>
<div class="h4">
	<?= I18N::translate('Usage of GEDCOM filters') ?>	
</div>
<a href="<?= e(route(SelectionPage::class)) ?>">
	<?= I18N::translate('Select GEDCOM import/export/conversion/datafix') ?>
</a>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<div class="h4">
		<?= I18N::translate('Settings for List Menu') ?>	
	</div>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Show menu item in list menu') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => MoreI18N::xlate('Show'), 'name' => DownloadGedcomWithURL::PREF_SHOW_MENU_LIST_ITEM, 'checked' => $show_menu_list_item]) ?>
				<div class="form-text">
					<?= I18N::translate('If this option is selected, a link to the %s page will be shown as a list menu item.', e($title)); ?>
				</div>
			</div>
		</div>
	</fieldset>		

	<div class="h4">
		<?= I18N::translate('Settings for Remote Requests via URL') ?>	
	</div>
	<?php if ($allow_remote_download) : ?>
		<div class="alert alert-warning">
			<p><?= I18N::translate('Currently, remote downloading of GEDCOM files is allowed. Please note that everyone with access to the authorization key, can download/upload/save GEDCOM files from/to your webtrees installation.') ?></p>
		</div>
	<?php endif ?>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Allow remote requests via URL to download GEDCOM files') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Allow'), 'name' => DownloadGedcomWithURL::PREF_ALLOW_REMOTE_DOWNLOAD, 'checked' => $allow_remote_download]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting this option, it is possible to activate remote downloads by calling an URL.'); ?>
				</div>
			</div>
		</div>
	</fieldset>		
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Allow remote requests via URL to save GEDCOM files to the server') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Allow'), 'name' => DownloadGedcomWithURL::PREF_ALLOW_REMOTE_SAVE, 'checked' => $allow_remote_save]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting this option, it is possible to activate remote requests to save GEDCOM files on the server via calling an URL.'); ?>
				</div>
			</div>
		</div>
	</fieldset>				
	<?php if ($allow_remote_upload) : ?>
		<div class="alert alert-danger">
			<p><?= I18N::translate('Currently, remote uploading of GEDCOM files is allowed. Please note that everyone with access to the authorization key, can download/upload/save GEDCOM files from/to your webtrees installation.') ?></p>
		</div>
	<?php endif ?>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Allow remote requests via URL to upload GEDCOM files') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Allow'), 'name' => DownloadGedcomWithURL::PREF_ALLOW_REMOTE_UPLOAD, 'checked' => $allow_remote_upload]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting this option, it is possible to activate remote uploads via calling an URL.'); ?>
				</div>
			</div>
		</div>
	</fieldset>		
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Allow remote requests via URL to convert GEDCOM files on the server') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Allow'), 'name' => DownloadGedcomWithURL::PREF_ALLOW_REMOTE_CONVERT, 'checked' => $allow_remote_convert]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting this option, it is possible to activate remote conversion of GEDCOM files on the server via calling an URL.'); ?>
				</div>
			</div>
		</div>
	</fieldset>		

	<div class="h4">
		<?= I18N::translate('Settings for the Authorization Key') ?>
	</div>
	<p><?= I18N::translate('An authorization key is needed if remote requests via URL shall be used.') ?></p>
	<div class="row mb-3">
		<?php if ($secret_key !== '' && !$use_hash) : ?>
			<div class="alert alert-warning">
				<p><?= I18N::translate('Currently, the authorization key is not encrypted. This option is less secure and should only be used in local environments with limited users. Otherwise, please activate encrpytion of the authorization key.') ?></p>
			</div>  
		<?php endif ?>
		<?php if (($allow_remote_download OR $allow_remote_save OR $allow_remote_upload OR $allow_remote_convert) && $secret_key === '') : ?>
			<div class="alert alert-danger">
				<p><?= I18N::translate('One of the options remote download/upload/save/convert is activated and the authorization key is empty or not available') ?></p>
			</div>  
		<?php endif ?>		
		<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Current authorization key') ?>
		</label>
		<?php if ($use_hash && ($secret_key !== '')) : ?>
			<?php $text_shown_for_secret_key = I18N::translate('The authorization key cannot be shown, because encryption is activated. If you forgot the key, you have to create a new key.')  ?>
		<?php elseif ($secret_key === '') : ?>
			<?php $text_shown_for_secret_key = I18N::translate('Authorization key has not been set yet')  ?>
		<?php else : ?>
			<?php $text_shown_for_secret_key = $secret_key  ?>
		<?php endif ?>
		<div class="col-sm-9 wt-page-options-value">
			<span class="input-group-text"><?= e($text_shown_for_secret_key) ?></span>
		</div>
	</div>				
	<div class="row mb-3">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="new_secret_key">
			<?= I18N::translate('New authorization key') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="new_secret_key" name="new_secret_key" type="text">
		</div>
	</div>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Activate encryption of the authorization key') ?>
			</legend>
			<div class="col-sm-9">
			<?= view('components/checkbox', ['label' => I18N::translate('Activate'), 'name' => DownloadGedcomWithURL::PREF_USE_HASH, 'checked' => $use_hash]) ?>
				<div class="form-text">
					<?= I18N::translate('The encryption of the authorization key is more secure, because the authorization key is not visible to anyone and also encrypted in the database. However, the authorization key is not readible any more (e.g. for other administrators) and cannot be recovered if it is forgotten.'); ?>
				</div>
			</div>
		</div>
	</fieldset>		

	<div class="h4">
		<?= I18N::translate('Setting for the Import/Export Folder on the webtrees Server') ?>	
	</div>
	<div class="row mb-3">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="folder_to_save">
			<?= I18N::translate('Folder name') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="folder_to_save" name="folder_to_save" type="text" value="<?= e($folder_to_save) ?>">
		</div>

		<?php $data_folder = str_replace('\\', '/', Registry::filesystem()->dataName()) ?>
		<?php $root_folder = str_replace('\\', '/', Registry::filesystem()->rootName()) ?>
		<?php $data_folder_relative = str_replace($root_folder, '', $data_folder) ?>

		<?php if (substr_compare($folder_to_save, $data_folder_relative, 0, strlen($data_folder_relative)) !== 0) : ?>
			<div class="alert alert-warning">
				<p>
					<?= I18N::translate('Currently, the folder to save is not a sub-directory of the webtrees data folder. It is highly recommended to use the webtrees data folder or a sub-directory, because webtrees protects unauthorized access to this folder. If you choose a folder outside of the webtrees data folder, the saved GEDCOM file might be unprotected against unauthorized access.' ) ?>
				</p>
			</div>  
		<?php endif ?>				

		<div class="form-text col-sm-9 offset-sm-3">
			<?= I18N::translate('Relative path to a folder within the webtrees root path, where GEDCOM import/exports are saved. It is highly recommended to use the webtrees data folder or a sub-directory, because webtrees protects unauthorized access to the data folder. The current settings (Control panel / Website preferences) for the webtrees root and data folder are:'); ?> 
			<br>
			<b><?= I18N::translate('webtrees root folder') ?>: </b>
			<?= Registry::filesystem()->rootName() ?>
			<br>
			<b><?= I18N::translate('webtrees data folder') ?>: </b>
			<?= Registry::filesystem()->dataName() ?>
			<br>
			<b><?= I18N::translate('webtrees data folder (relative path)') ?>: </b>
			<?= e($data_folder_relative) ?>
			<br>		
			<b><?= I18N::translate('webtrees data folder (setting in the control panel)') ?>: </b>
			<?= Site::getPreference('INDEX_DIRECTORY') ?>
		</div>			
	</div>

	<div class="h4">
		<?= I18N::translate('Default Settings for Gedcom Export') ?>
	</div>
	<p><?= I18N::translate('These settings are used as default values for exports, e.g. if certain parameter values are not provided within the URL. By specifying the default values, the URLs can be simplified. In the most extreme case, it is sufficient to provide the tree and the authorization key parameter only.') ?></p>	
	<p><?= I18N::translate('Any parameters provided in the URL of a remote download have a higher priority and will overrule the default settings.') ?></p>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Default privacy level') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => DownloadGedcomWithURL::PREF_DEFAULT_PRIVACY_LEVEL,'selected' => $default_privacy_level, 
					'options' => [
						'none'     => 'none (' . MoreI18N::xlate('None') .')', 
						'gedadmin' => 'gedadmin (' . MoreI18N::xlate('Manager') .')', 
						'user'     => 'user (' . MoreI18N::xlate('Member') .')',  
						'visitor'  => 'visitor (' . MoreI18N::xlate('Visitor') .')', 
					]
				]) ?>
				<div class="form-text">
					<?= I18N::translate('Select the default privacy level. This privacy level will be chosen if no specific privacy level is provided as URL parameter.')?>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Default export format') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => DownloadGedcomWithURL::PREF_DEFAULT_EXPORT_FORMAT, 'selected' => $default_export_format,
					'options' => [
						'gedcom'   => 'gedcom', 
						'zip'      => 'zip', 
						'zipmedia' => 'zipmedia (' . I18N::translate ('includes media files') .')', 
						'gedzip'   => 'gedzip (' . I18N::translate ('includes media files') .')', 
					]
				]) ?>
				<div class="form-text">
					<?= I18N::translate('Select the default export format. This export format will be chosen if no specific export format is provided as URL parameter.')?>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Default encoding') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => DownloadGedcomWithURL::PREF_DEFAULT_ENCODING, 'selected' => $default_encoding,
					'options' => [
						UTF8::NAME        => UTF8::NAME, 
						UTF16BE::NAME     => UTF16BE::NAME, 
						ANSEL::NAME       => ANSEL::NAME, 
						ASCII::NAME       => ASCII::NAME, 
						Windows1252::NAME => Windows1252::NAME,
					]
				]) ?>
				<div class="form-text">
					<?= I18N::translate('Select the default export format. This export format will be chosen if no specific export format is provided as URL parameter.')?>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Default ending') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => DownloadGedcomWithURL::PREF_DEFAULT_ENDING, 'selected' => $default_ending,
					'options' => [
						'CRLF' => 'CRLF (Windows)',
						'LF'   => 'LF (UNIX)',
					]
				]) ?>
				<div class="form-text">
					<?= I18N::translate('Select the default ending. This ending will be chosen if no specific ending is provided as URL parameter.')?>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Default time stamp') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/radios-inline', ['name' => DownloadGedcomWithURL::PREF_DEFAULT_TIME_STAMP, 'selected' => $default_time_stamp,
					'options' => [
						DownloadGedcomWithURL::TIME_STAMP_NONE    => DownloadGedcomWithURL::TIME_STAMP_NONE    . ' (' . I18N::translate('No time stamp') . ')',
						DownloadGedcomWithURL::TIME_STAMP_PREFIX  => DownloadGedcomWithURL::TIME_STAMP_PREFIX  . ' (' .  I18N::translate('Prefix time stamp') . ')',
						DownloadGedcomWithURL::TIME_STAMP_POSTFIX => DownloadGedcomWithURL::TIME_STAMP_POSTFIX . ' (' . I18N::translate('Postfix time stamp') . ')',
					] 
				]) ?>
				<div class="form-text">
					<?= I18N::translate('Select the default time stamp. This time stamp will be chosen if no specific time stamp is provided as URL parameter. If "none" is chosen, no time stamp will be used.')?>
				</div>
			</div>
		</div>
	</fieldset>	

	<div class="h4">
		<?= I18N::translate('Default Settings for GEDCOM Filters') ?>
	</div>		
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
		<?= I18N::translate('Default GEDCOM filter %s', '1') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', [
				'name' => DownloadGedcomWithURL::PREF_DEFAULT_GEDCOM_FILTER1, 
				'selected' => $default_gedcom_filter1, 
				'options' => $gedcom_filter_list,
				]) ?>
		</div>
		<div class="form-text col-sm-9 offset-sm-3">
			<?= I18N::translate('Select a default filter for GEDCOM filter %s. This filter will be chosen if no specific filter is provided as URL parameter.', '1'); ?>
		</div>
	</div>		
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Default GEDCOM filter %s', '2') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', [
				'name' => DownloadGedcomWithURL::PREF_DEFAULT_GEDCOM_FILTER2,
				'selected' => $default_gedcom_filter2,
				'options' => $gedcom_filter_list,
				]) ?>
		</div>
		<div class="form-text col-sm-9 offset-sm-3">
		<?= I18N::translate('Select a default filter for GEDCOM filter %s. This filter will be chosen if no specific filter is provided as URL parameter.', '2'); ?>
		</div>
	</div>		
	<div class="row mb-3">
		<label class="col-form-label col-sm-3">
			<?= I18N::translate('Default GEDCOM filter %s', '3') ?>
		</label>
		<div class="col-sm-9">
			<?= view('components/select', [
				'name' => DownloadGedcomWithURL::PREF_DEFAULT_GEDCOM_FILTER3,
				'selected' => $default_gedcom_filter3,
				'options' => $gedcom_filter_list,
				]) ?>
		</div>
		<div class="form-text col-sm-9 offset-sm-3">
		<?= I18N::translate('Select a default filter for GEDCOM filter %s. This filter will be chosen if no specific filter is provided as URL parameter.', '3'); ?>
		</div>
	</div>		
	<div class="row mb-3">
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('Save') ?>
			</button>
			<div class="form-text">
				<?= I18N::translate('In order to use changed settings for a download/upload, the settings need to be saved first.')?>
			</div>
		</div>		
	</div>		
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>